apiVersion: v1
kind: Pod
metadata:
  name: build-agent
  namespace: ci
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      image: maven:3.9.11-eclipse-temurin-21
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/
    - name: docker-tools
      image: rmkanda/docker-tools:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
        - mountPath: /tmp/trivycache/
          name: trivycache
#    - name: slscan
#      image: shiftleft/sast-scan:latest
#      imagePullPolicy: ifNotPresent
#      command:
#        - cat
#      tty: true
    - name: trufflehog
      image: rmkanda/trufflehog
      command:
        - cat
      tty: true
    - name: licensefinder
      image: licensefinder/license_finder
      command:
        - cat
      tty: true
  volumes:
    - name: m2
      hostPath:
        path: /tmp/.m2/
    - name: docker-sock
      hostPath:
        path: /var/run
    - name: trivycache
      hostPath:
        path: /tmp/trivycache/
    - name: reports
      hostPath:
        path: /home/user1/reports
    - name: jenkins-docker-cfg
      projected:
        sources:
        - secret:
            name: regcred
            items:
            - key: .dockerconfigjson
              path: config.json
      

